### ISSUE TITLE
Topics for CoP Meetings

### ISSUE THREAD

**Issue by gregpawin** [hackforla/engineering#10]
Please add ideas for topics that you want people to speak about.

**Comment by gregpawin** [comment]
Google Authentication

**Comment by akibrhast** [comment]
Jekyll Best Practices

**Comment by akibrhast** [comment]
Github Authentication

**Comment by jbubar** [comment]
Github actions

**Comment by akibrhast** [comment]
Jekyll Build Using Containers and TravisCI instead of doing the default github pages build

**Comment by gregpawin** [comment]
AWS

**Comment by gregpawin** [comment]
How to Use google sheets as a database

**Comment by gregpawin** [comment]
Oauth

**Comment by gregpawin** [comment]
Heroku

**Comment by bhaggya** [comment]
Github and AWS

**Comment by emecas** [comment]
Test Driven Development (TDD)

**Comment by emecas** [comment]
Git Flow

**Comment by emecas** [comment]
Specification by Example

**Comment by emecas** [comment]
Balance or point of convergence between the world of volunteering and good practices for software engineering (Technical Subjects / QA / Skills / Methodology / Tools)

**Comment by jbubar** [comment]
VSCODE extensions, and other fancy development environment setup things
