### ISSUE TITLE
Best Practices for Software Engineering in the Context of  Volunteering Work  - Talk Slides

### ISSUE THREAD

**Issue by emecas** [hackforla/engineering#20]
### Overview

Making available slides for the session:
**Best Practices for Software Engineering in the Context of  Volunteering Work**  
_Part # 1 About Metrics_
**Software Engineering Community of Practice** 
**04/21/2021**

### Action Items

 - [x] Add copy to google drive 
 - [ ] Add to this Repo

**Comment by qiqicodes** [comment]
Slides added to the Engineering CoP Google Drive
