### ISSUE TITLE
Feedbacks to make our community your favorite place =]

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/engineering#22]
Leave your thoughts down in the comment below

**Comment by jasonwong26** [comment]
Hack for LA Engineering Call
======


## check out the guides:
- [Hack for LA/Engineering/Templates and Guides](https://github.com/hackforla/engineering/projects/4)

## Documentation on how to to do Github stuffs per HackForLA Team
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests

Per Bonnie: work from the [Google Drive folder](https://drive.google.com/drive/folders/1xWllQli2wUSsRF9OaSQBBQ1vaY7kRkAT) when working on the guides.

All new folks should review Hack for LA guides
- [Kanban](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.nl3p4nf4eqb4)
- [Github contributing](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [Github reviewing](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)

**Comment by gregpawin** [comment]
Pair programming

**Comment by marcobarrera** [comment]
Great meeting. I'm also interested in pair programming!

**Comment by SLM-Dev** [comment]
I enjoyed this meeting. I learned a lot. It has been helpful in knowing the direction that engineers will be working together as well as everyone loving help, everyone seems to be on the same page, and Pair programming was a great idea by Hannah.

**Comment by hanapotski** [comment]
I really enjoy pair programming ❤️ so I'm looking forward to it! 🙌😁
