### ISSUE TITLE
Develop a method of deploying Docusaurus

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/engineering#36]
### Overview
We need a way to install Docusaurus easily on new repos, so that any org rep (who is not necessarily a programmer) can install it easily.

### Action Items
- [ ] Discuss if there is a way to create a base install that can be used over and over again (see below)
- [ ] If there is a way, set it up
- [ ] Test it with the https://github.com/hackforla/knowledgebase repo
- [ ] Write up instructions on how to us the way

### Resources/Instructions
https://v1.docusaurus.io/docs/en/tutorial-setup

#### Potential options to explore:
1.  A repo similar to .github but for docusaurus, that when a new repo is initialized we can use that and its branches as a template repo 
<details>
<summary>Screenshot of using template repo</summary>

![image](https://user-images.githubusercontent.com/37763229/205504916-ebee0530-0433-4d09-af0c-0eeb9c22d28f.png)
</details>

2. A Docker image

3. A GHA that will install it in a repo automatically

4. ???

**Comment by mxajPrice** [comment]
Org has decided MK Docs with material UI, this is being closed as "unplanned".  

See [this repo](https://github.com/hackforla/admin-new-project-provisioning), it has MK Docs installed.
