### ISSUE TITLE
Create list of channels with devs to do @here announcement to get attendance from every project

### ISSUE THREAD

**Issue by gregpawin** [hackforla/engineering#4]
### Overview
Invite devs from every Hack4LA project to the Engineering Community of Practice meeting on March 24.

### Action Items
- [ ] Create list of channels with devs
- [ ] Create announcement to invite devs to Engineering CoP meeting

### Resources

**Comment by ExperimentsInHonesty** [comment]
engineering (formerly developers) (34 members)  ·  Our Community of Practice for Software Engineers -A place where developers can get together and discuss effective practices for HfLA, technology, troubleshoot issues, and talk about career development.

1. 311-data-dev
2. fola-devs (53 members)
3. cti-devs (20 members)
4. engage-dev (140 members)
5. westside-dev-squad (18 members)
6. home-unite-us-dev (21 members)
7. vrms-devs (21 members)
8. 311-data-dev (32 members)
9. shared-housing-dev (43 members)
10. adopt-a-civicart-dev (19 members)
11. fola-devs-db (9 members)

**Comment by ExperimentsInHonesty** [comment]
Created a spreadsheet to identify if people have overlapping memberships between channels.
https://docs.google.com/spreadsheets/d/1tBrJ9xCZgLJFBG54oAztCERCm9-QxPErQUPANTLKgFQ/

**Comment by ExperimentsInHonesty** [comment]
I have notified all the channels that seemed appropriate (skipped adopt-a-civic-art-dev).

**Comment by ExperimentsInHonesty** [comment]
This is the decommissioning message
we are decommissioning this channel in the next 24 hours.  We will be inviting everyone in this channel to the #engineering channel

or

we are decommissioning this channel in the next 24 hours.  We will be inviting everyone in this channel to the #engineering channel
