### ISSUE TITLE
Engineering CoP: Gather best practices for speakers

### ISSUE THREAD

**Issue by MicahBear** [hackforla/engineering#40]
### Overview
Reach out to UI/UX CoP leads for their best practices and process for setting talks with speakers.

### Action Items
- [x] Meet with UI/UX CoP leads for their setup of templates/guides and process
  - Prep work for the speaker
            - Receiving questions from the community
            - Announcing the speaker to the community
            - Thank you response to the speaker
            - Sending questions to the speaker before the event
  - Discuss managing the actual speaking event practices
            - Length of talk

### Resources/Instructions
  - UI/UX CoP leads.
  - Research
       - Digital engagement strategies
       - Virtual Event Guides

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/UI-UX/issues/355
https://github.com/hackforla/UI-UX/wiki

**Comment by hkatzdev** [comment]
Google Drive Link: https://drive.google.com/drive/folders/1LAFurkHbkaoo7e_Rp_NgZzbEbVkOhTHH

**Comment by MicahBear** [comment]
### Event Registration
   - track amount attendees to start quantifying attendance at speaker events.
### Question and answer
   - collect the majority of questions prior to the event, and have a Q/A still available for stragglers.
### Live polling
   - if needed by the speaker
### Recorded content
   - record the event for availability later, and allow the slide/presentation for access later.
### Feedback surveys
   - get feedback from engineers about speaking event

**Comment by MicahBear** [comment]
Met with UI-UX CoP Co-Leads to talk about practices & ask questions.  Talk about templates, resources for GitHub issues, slack/email templates, process of contact with potential speaker, and selecting types of speakers.
