### ISSUE TITLE
Create program that will mark everyone on Google drive as a "Contributor"

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#45]
### Overview
THIS ISSUE NEEDS CLARIFICATION FROM BONNIE.  WILL ASK IN [NEXT COP LEAD MEETING](https://github.com/hackforla/engineering/issues/42#issuecomment-1481570336).

When new volunteers go through onboarding, they are added to their respective CoP Google Drives.  When they do this, they are automatically given the access level of "Content Manager" when they should be given "Contributor".  We need to create a program to make it easy to just set everyone to "Contributor" because it will be easier to just set a few people back to "Manager" than set everyone else to "Contributor". 

### Action Items
[To be filled in by engineer]

REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
Judson suggests we consider GAM for one-time permissions edit for everyone.
https://github.com/GAM-team/GAM

**Comment by mxajPrice** [comment]
Judson suggests we consider GAM for one-time permissions edit for everyone.
https://github.com/GAM-team/GAM

**Comment by hkatzdev** [comment]
Related Issue: https://github.com/hackforla/tables/issues/36

**Comment by mxajPrice** [comment]
This issue is no longer needed.  VRMS took care of the issue.
