### ISSUE TITLE
Get basic wiki started

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#46]
### Overview
We don't have a wiki!  Let's take a look at other CoP wikis to see what kind of information they are putting on theirs that would work well for ours, adding or omitting as suits the needs of the community.  

### Action Items

- [x] Look at other CoP wikis and list what information they are putting on theirs
- [x] Wittle down what basic things we can add to ours 
- [x] create outline for our wiki
- [x] create issues to build out each section of the wiki

### Resources/Instructions
- Other established CoP wikis:
    - [UX/UI](https://github.com/hackforla/UI-UX/wiki)
    - [Data Science](https://github.com/hackforla/data-science/wiki)
    - [Ops](https://github.com/hackforla/ops/wiki)
    - [Product Management](https://github.com/hackforla/product-management/wiki)
- [Wiki template guide](https://github.com/hackforla/admin/issues/36#issuecomment-770112547)

**Comment by mxajPrice** [comment]
UX/UI
-

**Comment by mxajPrice** [comment]
Outline:

Welcome to the Eng CoP!
How to join
Programming
- Speakers
- Mentoring Nights
- Lightning Talks
Leadership Team

**Comment by MicahBear** [comment]
@mxajPrice Is the Mentorship Team header us? or folks who sign up to mentor?

**Comment by mxajPrice** [comment]
Issues have been created and listed in the epic issue #50.  This issue is complete.
