### ISSUE TITLE
Questions for 2023-05-25: Jordan Harband | Open-Source Maintainer

### ISSUE THREAD

**Issue by agosmou** [hackforla/engineering#60]
### Overview
Please comment the topics/questions you would like to hear about from tenured industry developer, Jordan Harband. Feel free to comment on anything else regarding guest speakers.

**Comment by agosmou** [comment]
How would you recommend novice OSS devs find projects to work on throughout their careers?
- Should they consider the tools and software they use?
- At first, should this be limited to only languages they know?

What resources and knowledge could you offer to novice OSS devs about contributing more to OSS projects and getting involved with the OSS community?

**Comment by abuna1985** [comment]
1. What’s an essential lesson you learned as a result of failure?
2. Can you share any success stories or memorable moments you've had as an open source maintainer that have made a significant impact on your journey?
3. Have you ever had to deal with burnout as an open source maintainer/engineer? How do you manage and prevent burnout in your role?
4. What are some future trends in the open source/JavScript/web development landscape that you're excited about?

**Comment by agosmou** [comment]
In 2023, what non-negotiables (technical skills, certifications, soft skills) should a junior dev showcase:

1. on their resume to be more marketable
2. while interviewing to increase hire-ability
3. on the job to succeed as a junior and escalate to mid/senior position

**Comment by agosmou** [comment]
(Community Sourced Questions)
- What are some proposals going through tc39 you liked?
- How was working with the folk of tc39?
- Since the early days of javascript, what’s been the main thing from your perspective that’s enabled mass adoption?

**Comment by agosmou** [comment]
What are security-related best practices when working on OSS?

**Comment by agosmou** [comment]
When looking at open issues across many different open source projects, I see many of them are from multiple years ago. My gut reaction is to dismiss anything that is not recent.

What are your thoughts on this?

**Comment by kerimedeiros** [comment]
- What are some of the challenges you've faced at various companies when starting an Open Source program from scratch? And did these challenges differ depending on the company culture, size, infrastructure, etc. (for example: Coinbase vs. Opendoor vs. Airbnb)? 

- Any advice for those who are looking to get more involved in OSS programs at their current company (or kick starting OSS efforts if not yet established)?
