### ISSUE TITLE
Generate Questions for 2023-05-25: Jordan Harband | Open Source Maintainer

### ISSUE THREAD

**Issue by agosmou** [hackforla/engineering#63]
### Overview
We need to create a list of questions for our guest speaker, Jordan Harband, attending on 2023-05-25.

### Action Items
- [x] Send issue to Engineering Slack channel and ask Engineering members to write their questions in the comments.
- [x] Collate the questions into a list of unique questions (non-duplicated questions).
- [x] Send them to the guest speakers within 2 weeks of their talk.

### Resources/Instructions
<details>
<summary>Slack Announcement </summary>

**[GUEST SPEAKER]** will be visiting the Engineering Community of Practice on **[DATE]**!

**Topic:** [Input Discussion Topic]
  
Please post **your questions** in this [GitHub issue] 
  
**About:** [INSERT BIO] 

**[LinkedIn or WEBSITE]** [LINKEDIN LINK]

We will be collecting questions until the end of day : [Date of last day]

Thank you!
Engineering CoP co-leads

</details>

- [WEBSITE FOR GUEST SPEAKER]

### Speaker Bio
[INSERT SPEARKER BIO]

**Comment by agosmou** [comment]
https://github.com/hackforla/engineering/issues/60

**Comment by MicahBear** [comment]
Added this issue to our tracker.
