### ISSUE TITLE
Questions for 2023-06-15: Sukrutha Bhadouria | Salesforce & Girl Geek X

### ISSUE THREAD

**Issue by agosmou** [hackforla/engineering#68]
### Overview

Please comment the topics/questions you would like to hear about from tenured industry developer, Sukrutha Bhadouria. Feel free to comment on anything else regarding guest speakers.

**Comment by agosmou** [comment]
## Background
What has set you apart (qualities, opportunities, projects/assignments, education, etc) as a software engineer to be able to escalate from a dev through management and into a director position?

## Engineering Leadership
What is the recipe for an excellent engineering team (management and developers)?

What qualities in engineering devs would you like to see that would set candidates apart in 2023 (junior devs, mid level devs, senior devs?)

## Diversity
As an underrepresented minority (URM), what were some of the challenges you faced and how did you overcome them?

Has the tech industry improved for URM? In what ways? 

What was the driving force to co-found Girl Geek X? What are some of the effects your organization has had on the broader URM community?


## Mentorship, Community, and Life
You have a lot of mentorship experience; being that this is a large time commitment, what can you suggest to Hack for LA members to encourage them to seek mentorship opportunities?

What superhuman powers do you have that help you balance your involvement with Girl Geek X, work at Salesforce, extracurricular organizations, and motherhood?

**Comment by one2code** [comment]
1. What qualities should new developers focus on developing- both tech and non-tech - to stand out in today's competitive tech market? 
2.  In your experience, what is the number one thing that new hires could generally improve on?
3. What is your ideal 6 month and 1 year roadmap for new developers you hire into your department?
4. What advice do you have for a job applicant looking to stand out amongst the pool of 1000's of applicants?
5. Do you have any fears for the tech market in the near future? If so, what are they?
6.  What can we do as developers, to improve diversity, equity, and inclusion, and make the tech space more fair and equitable?
