### ISSUE TITLE
Review and consolidate Hack for LA homepage technology filter list

### ISSUE THREAD

**Issue by daniellex0** [hackforla/engineering#7]
### Overview
We need to review and consolidate the technology filter options for projects on the Hack for LA website homepage, in order to remove the redundant options. 

The final technology list will be provided as options to choose from for new project cards, so that the same technologies will no longer be written differently on different project cards.

### Action Items
- [ ] Review all of the technology filter options currently on the HfLA site homepage (see list below under resources)
- [ ] Consolidate the list to remove any repeat technologies (leave each type of technology with one official name for the filter)
- [ ] Comment the final list in this issue so that @daniellex0 and the HfLA site team can update the technology filter options

### Resources/Instructions
[Hack for LA homepage](https://www.hackforla.org/#)

**Click arrow below to view current technology list:**

<details>
<summary>View current full technology filter list</summary>
<br>

- AWS (2)
- Adobe CC (1)
- Auth0 / OIDC / OAuth2 (1)
- Azure App Service (1)
- Code Climate (1)
- Cypress (1)
- Django (2)
- Docker (5)
- ESLint (1)
- Express (4)
- FastAPI (1)
- Figma (3)
- Flask (1)
- Flutter (1)
- GeoPandas (1)
- GitHub Pages (2)
- ~Google Docs (1)~
- ~Google Docs (Doc, Sheet, Slide, Forms) (1)~
- ~Google Sheets (1)~
- ~HackforLA.org guides (1)~
- Jekyll (2)
- Jest (1)
- Leaflet (1)
- Mapbox (3)
- Markdown (1)
- Material-UI (2)
- Microsoft SQL Server (1)
- Miro (2)
- MongoDB (3)
- NoSQL (1)
- Node (1)
- Node.js (5)
- PostGIS (1)
- PostgreSQL (5)
- Prefect (1)
- Python (1)
- Python 3 (1)
- React (1)
- React Native (1)
- React Testing Library (1)
- ReactJS (10)
- Redis (1)
- Redux (2)
- SCSS (2)
- Sass (1)
- TypeScript (1)
- jQuery (1)

</details>

<br>
<br>

<img width="450" alt="Screen Shot 2021-03-19 at 12 18 31 AM" src="https://user-images.githubusercontent.com/67400366/111744590-b031ab00-8848-11eb-9eb2-9058864648c8.png">

**Comment by gregpawin** [comment]
Node.js, React, Python, SASS, add Java, SpringBoot

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 the list above is the final names we choose for anything that falls into that bucket.   I have opened this issue https://github.com/hackforla/website/issues/1346 to get those changes made on the hackforla website team.
