### ISSUE TITLE
Recruit new Engineering CoP lead

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#77]
### Overview

We need a lead to help us out with coordinating Mentors.

### Action Items
- [x] Post [card](https://github.com/hackforla/engineering/projects/2#card-90139782) on Open Roles board
- [x] Post in [Community Leads Open Roles wiki](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles)
- [x] Notify community in [#Engineering Slack](https://hackforla.slack.com/archives/C01CU709SER)
- [ ] Notify community in CoP meeting
- [ ] Host an info session with interested parties
- [x] Interview candidates with the other leads to make sure:
   - They are able to commit to at least 6 months
   - They are available to come to Thursday meetings
   - They are able to participate in meaningful conversation and interested in community development ('Why are you interested in this role?)
- [x] Onboard the selected new lead

### Resources/References
- Open Roles Cards
   - [Mentor Coordinator](https://github.com/hackforla/engineering/projects/2#card-90139782)
- Open Roles wiki
   - [Mentor Coordinator](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-cop-community-co-lead---mentor-coordinator)
- Recruitment forms can be found [here](https://drive.google.com/drive/u/0/folders/1A8KSPEQ5oupkp5iCK53Xu85lh7Wm7q0r)

**Comment by chelseybeck** [comment]
Adam Abundis is our mentor coordinator :smile:

**Comment by chelseybeck** [comment]
Adam Abundis is our mentor coordinator :smile:
