### ISSUE TITLE
Lead Dev Role for 311 Data

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/engineering#95]
<img src="https://www.hackforla.org/assets/images/projects/311_data.png" />

**Project Name:** 311-Data

**About**: 311-Data.org is a data visualization and analytics tool. We help local governments throughout the City of LA make better data-informed decisions. Come join us as we build software that democratizes data and impacts millions of people. 

**Volunteer Opportunity**: Lead Developer. React fluency required, tech lead experience preferred. Our tech stack is frontend only.

**Tech Stack:** JavaScript, React.js

**Duration:** Open-ended

**Meeting times**: Wednesdays @7:00 pm PST

**Interested? Connect with us** 

  - Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
  - Slack DM:  [Ryan - Eng / PM](https://hackforla.slack.com/team/U052L9R6ETD) 

[Read more about the project](https://www.hackforla.org/projects/311-data)
[311-Data.org](www.311.data.org)

**Comment by heejung-hong** [comment]
Card has been created and in the Engineering Job Board.
